apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: uptime-alert
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: uptime-alert
              image: xobed/uptime-alert
              env:
                - name: MONITORED_URLS
                  value: {{ required "monitored_urls is required" .Values.monitored_urls }}
                - name: SENTRY_DSN
                  value: {{ required "sentry_dsn is required" .Values.sentry_dsn }}
                - name: RETRY_LIMIT_SECONDS
                  value: {{ .Values.retry_limit_seconds | quote }}
